services:
  postgres:
    container_name: minipong-postgres
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  gateway:
    container_name: minipong-gateway
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    env_file:
      - services/gateway/.env
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./shared/logger/src:/usr/src/app/shared/logger/src
      - ./shared/kafka/src:/usr/src/app/shared/kafka/src
      - ./shared/gprc-client-manager/src:/usr/src/app/shared/gprc-client-manager/src
      - ./services/gateway/src:/usr/src/app/services/gateway/src/
      - ./services/gateway/package.json:/usr/src/app/services/gateway/package.json
    command: pnpm dlx turbo run dev --parallel

  auth:
    container_name: minipong-auth
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    env_file:
      - services/auth/.env
    volumes:
      - ./shared/logger/src:/usr/src/app/shared/logger/src
      - ./shared/kafka/src:/usr/src/app/shared/kafka/src
      - ./shared/gprc-client-manager/src:/usr/src/app/shared/gprc-client-manager/src
      - ./services/auth/src:/usr/src/app/services/auth/src/
      - ./services/auth/package.json:/usr/src/app/services/auth/package.json
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: pnpm dlx turbo run dev --parallel

  profile:
    container_name: minipong-profile
    build:
      context: .
      dockerfile: services/profile/Dockerfile
    env_file:
      - services/profile/.env
    volumes:
      - ./shared/logger/src:/usr/src/app/shared/logger/src
      - ./shared/kafka/src:/usr/src/app/shared/kafka/src
      - ./shared/gprc-client-manager/src:/usr/src/app/shared/gprc-client-manager/src
      - ./services/profile/src:/usr/src/app/services/profile/src/
      - ./services/profile/package.json:/usr/src/app/services/profile/package.json
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: pnpm dlx turbo run dev --parallel

  engine:
    container_name: minipong-engine
    build:
      context: .
      dockerfile: services/engine/Dockerfile
    env_file:
      - services/engine/.env
    volumes:
      - ./shared/logger/src:/usr/src/app/shared/logger/src
      - ./shared/kafka/src:/usr/src/app/shared/kafka/src
      - ./shared/gprc-client-manager/src:/usr/src/app/shared/gprc-client-manager/src
      - ./services/engine/src:/usr/src/app/services/engine/src/
      - ./services/engine/package.json:/usr/src/app/services/engine/package.json
    command: pnpm dlx turbo run dev --parallel

  fallout:
    container_name: minipong-fallout
    build:
      context: .
      dockerfile: services/fallout/Dockerfile
    env_file:
      - services/fallout/.env
    volumes:
      - ./shared/logger/src:/usr/src/app/shared/logger/src
      - ./shared/kafka/src:/usr/src/app/shared/kafka/src
      - ./shared/gprc-client-manager/src:/usr/src/app/shared/gprc-client-manager/src
      - ./services/fallout/src:/usr/src/app/services/fallout/src/
      - ./services/fallout/package.json:/usr/src/app/services/fallout/package.json
    command: pnpm dlx turbo run dev --parallel

  kafka:
    image: apache/kafka:4.0.1
    container_name: minipong-kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      # Указываем роли узла
      KAFKA_PROCESS_ROLES: broker,controller
      # Уникальный ID узла
      KAFKA_NODE_ID: 1
      # Кластер ID (можно сгенерировать через kafka-storage.sh random-uuid)
      KAFKA_CLUSTER_ID: kraft-cluster-001
      # Настройка контроллера
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      # Лог директория
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    volumes:
      - ./services/kafka/log:/tmp/kraft-combined-logs
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/127.0.0.1/9092"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

#  mongo:
#    container_name: minipong-mongo
#    image: mongo:8
#    restart: always
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongo
#      MONGO_INITDB_ROOT_PASSWORD: mongo
#      MONGO_INITDB_DATABASE: minipong
#    volumes:
#      - mongo_data:/data/db
#    healthcheck:
#      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
#
#  mail:
#    container_name: minipong-mail
#    build:
#      context: .
#      dockerfile: services/mail/Dockerfile
#    env_file:
#      - services/mail/.env
#    volumes:
#      - ./services/mail/:/usr/src/app/
#      - /usr/src/app/node_modules
#    command: pnpm dlx turbo run dev --parallel
#    depends_on:
#      postgres:
#        condition: service_healthy
#
#  mailpit:
#    image: axllent/mailpit
#    container_name: minipong-mailpit
#    ports:
#      - 8025:8025
#      - 1025:1025
#    environment:
#      MP_WEBROOT : "/mailpit/"
##      MP_SMTP_AUTH_ACCEPT_ANY: 1
#      MP_SMTP_AUTH_ALLOW_INSECURE: 1
#      MP_SMTP_AUTH: "login:pass"
#      MP_MAX_MESSAGES: 5000
#    volumes:
#      - /data
#    restart: always
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

volumes:
  postgres_data:
  kafka_data:
  mongo_data: