// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANQYaEgxMJU2B9cuXpigEd3Lz19odZvns',
    appId: '1:1011044035242:web:3f671dcb7654cf716b3ed3',
    messagingSenderId: '1011044035242',
    projectId: 'minipong',
    authDomain: 'minipong.firebaseapp.com',
    storageBucket: 'minipong.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwag02bDTaYtY7aBe1YmGo3rt-FE32oBM',
    appId: '1:1011044035242:android:0f9f09932f1106ca6b3ed3',
    messagingSenderId: '1011044035242',
    projectId: 'minipong',
    storageBucket: 'minipong.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIS8Uz_g4EbObU-JNWW9IxOSJSLY1uJsA',
    appId: '1:1011044035242:ios:65b8a7516c7ee9f26b3ed3',
    messagingSenderId: '1011044035242',
    projectId: 'minipong',
    storageBucket: 'minipong.firebasestorage.app',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIS8Uz_g4EbObU-JNWW9IxOSJSLY1uJsA',
    appId: '1:1011044035242:ios:65b8a7516c7ee9f26b3ed3',
    messagingSenderId: '1011044035242',
    projectId: 'minipong',
    storageBucket: 'minipong.firebasestorage.app',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANQYaEgxMJU2B9cuXpigEd3Lz19odZvns',
    appId: '1:1011044035242:web:34f4fd7e11a7b2966b3ed3',
    messagingSenderId: '1011044035242',
    projectId: 'minipong',
    authDomain: 'minipong.firebaseapp.com',
    storageBucket: 'minipong.firebasestorage.app',
  );
}
